name: wpe
version: '0.1'
base: core18
summary: WebKit port for embedded and low-consumption computer devices
description: |
  WPE is the reference WebKit port for embedded and low-consumption
  computer devices. It has been designed from the ground-up with
  performance, small footprint, accelerated content rendering, and
  simplicity of deployment in mind, bringing the excellence of the
  WebKit engine to countless platforms and target devices.

grade: stable
confinement: strict

parts:
  libwpe:
    source: https://wpewebkit.org/releases/libwpe-1.1.0.tar.xz
    plugin: cmake
    build-packages:
      - libgles2-mesa-dev
      - libxkbcommon-dev
  wpebackend:
    source: https://wpewebkit.org/releases/wpebackend-fdo-1.1.0.tar.xz
    plugin: cmake
    after: [ libwpe ]
  wpe:
    source: git://git.webkit.org/WebKit.git
    source-depth: 1
    plugin: cmake
    override-build: |
      cmake $SNAPCRAFT_PART_SRC \
        -DCMAKE_INSTALL_PREFIX= \
        -DPORT=WPE \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -GNinja
      ninja
      ninja install
    build-packages:
      - build-essential
      - cmake
      - g++
      - gperf
      - libcairo2-dev
      - libepoxy-dev
      - libgcrypt20-dev
      - libgstreamer-plugins-base1.0-dev
      - libharfbuzz-dev
      - libjpeg-dev
      - libopenjp2-7-dev
      - libsoup2.4-dev
      - libsqlite3-dev
      - libtasn1-6-dev
      - libtool-bin
      - libwebp-dev
      - libwoff-dev
      - libxml-libxml-perl
      - libxslt1-dev
      - ninja-build
      - pkg-config
      - ruby-dev
    after: [ libwpe, wpebackend ]
